[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
onchain_community = "wNSuywSzp36Q3TgeaCJnBjie1pMpHPbxAzkkvvUKnaX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hoooooou_jun/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
